keys:
- &users:
  - &flamin age1r60mmg8sm492596tauljym8pmch62qcc2xku6vs74gszj23dp4jskuwege
- &hosts:
  - &satis age1wltghmj30xjw9e5vcsncwksz8fmmnjlctt0hgjh02vhr5xsctgrquv2zlq
  - &vestalod age1tjrhtpuwlnkzddj0872xulrtzt0efr2atpf6gnl0q38q5k6gyces5vgqnz
  - &hathor age1wpp7q5vhywcj0yq33t883qsg76mk7a69y9vut4rxkzfg5zxyea2s5j4mms
creation_rules:
- path_regex: secrets.yaml$
  key_groups:
    - age:
      - *flamin
      - *satis
      - *vestalod
      - *hathor
